"""Remove association table 

Revision ID: 98e031a46e57
Revises: bbac7286327a
Create Date: 2022-07-18 18:43:52.545844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98e031a46e57'
down_revision = 'bbac7286327a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_like_playlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_like_playlist',
    sa.Column('user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('playlist', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['playlist'], ['playlists.id'], name='user_like_playlist_ibfk_1'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='user_like_playlist_ibfk_2'),
    sa.PrimaryKeyConstraint('user', 'playlist'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
